fix(deps): add @semantic-release/git as dependency
semantic-release/semantic-release pull request #2692
Opened 2023-01-26 14:34 UTC by tada5hi

2023-01-29 19:25 UTC, 121data approved these changes

2023-01-29 19:28 UTC, 121data approved these changes

2023-01-30 03:43 UTC, travi commented
closing based on the reasons stated in https://github.com/semantic-release/semantic-release/issues/2691#issuecomment-1407951127

2023-01-30 03:43 UTC, closed without merging

2023-01-30 05:22 UTC, 121data requested changes
Dcvh

2023-01-30 05:23 UTC, 121data reviewed
@121data